export const ADD_MOVIE = 'ADD_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
export const RECEIVE_MOVIES = 'RECEIVE_MOVIES';

export const CHANGE_SINGLE_VALUE = 'CHANGE_SINGLE_VALUE';
export const RECEIVE_SINGLE_VALUE = 'RECEIVE_SINGLE_VALUE';

export const ADD_TO_VALUE_LIST = 'ADD_TO_VALUE_LIST';
export const REMOVE_FROM_VALUE_LIST = 'REMOVE_FROM_VALUE_LIST';
