export const ADD_MOVIE = 'ADD_MOVIE';
export const EDIT_NEW_MOVIE_VALUE = 'EDIT_NEW_MOVIE_VALUE';
export const UPDATE_VALUE = 'UPDATE_VALUE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const CLEAR_NEW_MOVIE = 'CLEAR_NEW_MOVIE';
export const SAVE_MOVIES = 'SAVE_MOVIES';
